/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MapRouteImport } from './routes/map'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'
import { Route as PapersSlugRouteImport } from './routes/papers.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/chapters/$slug',
  path: '/chapters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersSlugRoute = PapersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PapersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/papers': typeof PapersRouteWithChildren
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/papers/$slug': typeof PapersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/papers': typeof PapersRouteWithChildren
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/papers/$slug': typeof PapersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/papers': typeof PapersRouteWithChildren
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/papers/$slug': typeof PapersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/map' | '/papers' | '/chapters/$slug' | '/papers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/map' | '/papers' | '/chapters/$slug' | '/papers/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/map'
    | '/papers'
    | '/chapters/$slug'
    | '/papers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MapRoute: typeof MapRoute
  PapersRoute: typeof PapersRouteWithChildren
  ChaptersSlugRoute: typeof ChaptersSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/chapters/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$slug': {
      id: '/papers/$slug'
      path: '/$slug'
      fullPath: '/papers/$slug'
      preLoaderRoute: typeof PapersSlugRouteImport
      parentRoute: typeof PapersRoute
    }
  }
}

interface PapersRouteChildren {
  PapersSlugRoute: typeof PapersSlugRoute
}

const PapersRouteChildren: PapersRouteChildren = {
  PapersSlugRoute: PapersSlugRoute,
}

const PapersRouteWithChildren =
  PapersRoute._addFileChildren(PapersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MapRoute: MapRoute,
  PapersRoute: PapersRouteWithChildren,
  ChaptersSlugRoute: ChaptersSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
